### ISSUE TITLE
初始化动态渲染状态

### ISSUE THREAD

**Issue by Fengmaybe** [AJLoveChina/vue-clap-button#5]
对于使用的icon  可以初始化他的状态 比如目前初始化都是没有点击的灰色状态  但是 有些逻辑 是初始化状态是已点击赞的状态，，如何修改源码呢？我看了了一下  都修改失败了。好像配合isActive和clickTime无法控制。

**Comment by zy-swj** [comment]
兄弟，这个问题解决了吗

**Comment by AJLoveChina** [comment]
@Fengmaybe @zy-swj   谢谢老铁们的关注,  迟来的修改, 已经上线 vue-clap-button@1.0.6
![image](https://user-images.githubusercontent.com/11222746/96398394-56c44200-11fe-11eb-8ea7-149a4a075fb1.png)

**Comment by chengyu2333** [comment]
新版本好像还是没解决哦

**Comment by chengyu2333** [comment]
> 新版本好像还是没解决哦

好像只能初始化，但是不能动态更新initClicked
